Allow for manual crafting of Rush! beatmaps with osu! stable
swoolcock/rush pull request #48
Opened 2020-08-15 08:43 UTC by swoolcock

Adds a separate beatmap converter that allows mappers to craft Rush!-specific beatmaps using the stable osu! editor.  Conversion details are in xmldoc.

I'll include a test map with the next release.

2020-08-18 18:21 UTC, frenzibyte requested changes
I've pushed two tests, one for the beatmap conversion deciding test (whether crafted or generated), and a runnable `BeatmapConversionTest<TConvertValue>`, haven't included an expected result as I don't have much time to look at it, you can check the base class test and the existing test fixtures across legacy rulesets to understand how to make one.

Looks good to go otherwise, really like the fact that I can make a rush! beatmap inside osu!lazer (just need setup screen now), good job on this. 👍

2020-08-19 00:17 UTC, swoolcock commented on osu.Game.Rulesets.Rush/Beatmaps/RushCraftedBeatmapConverter.cs
> +        public override bool CanConvert() => true;
As discussed, I’m not sure if there are performance considerations with using linq there. I figured it was safer to leave it as is.

2020-08-19 00:19 UTC, frenzibyte commented on osu.Game.Rulesets.Rush/Beatmaps/RushCraftedBeatmapConverter.cs
> +        public override bool CanConvert() => true;
Oh right forgot about that one, anyways confirmed above that the method is called when a beatmap is started, so should have no performance impact whatsoever.

2020-08-19 00:20 UTC, swoolcock commented on osu.Game.Rulesets.Rush/Beatmaps/RushCraftedBeatmapConverter.cs
> +    /// G: 400,300
Possibly, but I personally did the entire mapping of the crafted map in VS Code. :P

2020-08-19 07:20 UTC, swoolcock commented on osu.Game.Rulesets.Rush/Beatmaps/RushCraftedBeatmapConverter.cs
> +        public override bool CanConvert() => true;
I foresee it being called more than that tbh.  Needs to be able to available at any time for filtering beatmaps.  I'll make this change in the future.

2020-08-19 07:24 UTC, merged